# Generated by Django 5.2.1 on 2025-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
