# Generated by Django 5.2.1 on 2025-07-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faqs',
        ),
        migrations.AddField(
            model_name='profile',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
