# Generated by Django 5.2.1 on 2025-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_faqs_profile_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faqs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
