# Generated by Django 5.2.4 on 2025-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_profile_contact_number_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
