# Generated by Django 5.2.4 on 2025-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_contact_number_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
